[deploy]
startCommand = "cd slt && python manage.py migrate --noinput && gunicorn slt.wsgi"

[deploy.envVars]
DB_HOST = "${{MySQL.MYSQLHOST}}"
DB_PORT = "${{MySQL.MYSQLPORT}}"
DB_USER = "${{MySQL.MYSQLUSER}}"
DB_PASSWORD = "${{MySQL.MYSQLPASSWORD}}"
DB_NAME = "${{MySQL.MYSQLDATABASE}}"
