# Generated by Django 6.0.3 on 2026-06-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusprogress',
            name='completed_term_indices',
            field=models.JSONField(default=list),
        ),
    ]
