# Generated by Django 4.2.29 on 2026-05-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verification_token',
        ),
    ]
